# Generated by Django 4.2.16 on 2024-10-25 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='time_request',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_request',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
