# Generated by Django 4.2.16 on 2024-10-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_bookingrequest_time_request_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Contact',
        ),
    ]
