# Generated by Django 4.2.16 on 2024-10-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_about_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='About',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='message',
            field=models.TextField(),
        ),
    ]
